print("Que sale de la cruza de un mono y un pato")
input()
print("Un monopatin!")
print()
print("Porque vuelan los pajaros para el sur")
input()
print("Porque caminando tardarian muchisimo")
print()
print("En que se parecen una familia, un bombero y un barco")
input()
print("No se, en que se parecen?")
input()
print("En que el bombero y el barco tienen casco")
input()
print("Y la familia?", end="")
print("Bien gracias")
